name: CI Checks

on:
  push:
    branches:
      - main
      - develop
      - nastia/fix/cpu_test
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: JVM tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :vpn-impl:testDebugUnitTest --tests "com.duckduckgo.mobile.android.vpn.health.AppTPCPUMonitorTest"
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: app-tracking-protection/vpn-impl/build/test-results/testDebugUnitTest/binary/output.bin
